import { Alert } from "react-native";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "../../../lib/supabase";
import { logger } from "../../../utils/logger";
import { logActivity } from "../../../utils/activityLogger";
import { feedKeys } from "../../communities/data/queryKeys";
import { commentKeys } from "../data/queryKeys";
import type { Database } from "../../../types/database.types";
import type { CommentNode, CommentVM } from "../utils/tree";

type Profile = Database["public"]["Tables"]["profiles"]["Row"];

type CreateCommentInput = {
  content: string;
  parentId: string | null;
  isAnonymous: boolean;
  /**
   * Idempotency key for this submission (Phase 4). Generated by the caller
   * (post/[id].tsx) and held stable across retries of the same content —
   * see lastCommentAttemptRef there for why the id can't be generated here,
   * inside the mutation.
   */
  id: string;
};

type UseCreateCommentOptions = {
  postId: string | null | undefined;
  viewerId: string | null;
  /**
   * The post's community (null for Campus Feed). When provided, scopes the
   * feed-row refresh (comment_count) to just that community instead of
   * every mounted Campus/community feed. Falls back to the previous
   * broad-but-lazy invalidation when omitted.
   */
  communityId?: string | null;
};

export function useCreateComment({
  postId,
  viewerId,
  communityId,
}: UseCreateCommentOptions) {
  const queryClient = useQueryClient();
  const listKey = commentKeys.list(postId, viewerId);

  // The viewer's profile is almost always cached (useMyProfile); only fall
  // back to a network read if it isn't.
  const getViewerProfile = async (): Promise<Profile | undefined> => {
    if (!viewerId) return undefined;
    const cached = queryClient.getQueryData<Profile | null>(["current-user-profile", viewerId]);
    if (cached) return cached;
    const { data } = await supabase.from("profiles").select("*").eq("id", viewerId).single();
    return data ?? undefined;
  };

  const removeComment = (id: string) => {
    queryClient.setQueryData<CommentVM[]>(listKey, (old) => old?.filter((c) => c.id !== id));
  };

  return useMutation({
    mutationFn: async ({ content, parentId, isAnonymous, id }: CreateCommentInput) => {
      if (!viewerId) {
        throw new Error("You must be logged in to post a comment");
      }
      if (!postId) {
        throw new Error("Post ID is required");
      }

      const supabaseUrl = process.env.EXPO_PUBLIC_SUPABASE_URL!;
      const functionUrl = `${supabaseUrl}/functions/v1/create-comment`;

      // Refresh session so the token is valid (fixes "Unauthorized" on simulator / stale tokens)
      const { data: refreshData, error: refreshError } =
        await supabase.auth.refreshSession();
      const session =
        refreshData?.session ?? (await supabase.auth.getSession()).data?.session;

      if (refreshError) {
        logger.error("Session refresh failed", refreshError);
        throw new Error("Session expired. Please sign in again.");
      }
      if (!session?.access_token) {
        throw new Error("You must be logged in to post a comment.");
      }

      const safeParentId =
        parentId && !parentId.startsWith("temp-") ? parentId : null;

      const commentPayload = {
        id,
        content: content.trim(),
        post_id: postId,
        parent_comment_id: safeParentId,
        is_anonymous: isAnonymous,
      };

      const response = await fetch(functionUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${session.access_token}`,
          apikey: process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY!,
        },
        body: JSON.stringify(commentPayload),
      });

      const responseData = await response.json();

      if (!response.ok) {
        const rawMessage =
          responseData?.error || responseData?.message || "Failed to create comment";
        const errorMessage =
          rawMessage === "Unauthorized"
            ? "Session expired or invalid. Please sign in again."
            : rawMessage;
        throw new Error(errorMessage);
      }

      if (responseData?.error) {
        throw new Error(responseData.error);
      }

      if (!responseData || !responseData.id) {
        throw new Error("Invalid response from server");
      }

      return responseData as CommentNode;
    },
    onMutate: async ({ content, parentId, isAnonymous, id }: CreateCommentInput) => {
      if (!viewerId || !postId) return;
      // Stop an in-flight fetch from overwriting the optimistic entry.
      await queryClient.cancelQueries({ queryKey: listKey });

      const existing = queryClient.getQueryData<CommentVM[]>(listKey) ?? [];
      // post_specific_anon_id is assigned server-side and is stable per
      // (post, user) — reuse the viewer's existing number on this post so the
      // optimistic comment already shows the right "User N".
      const knownAnonId = isAnonymous
        ? existing.find((c) => c.user_id === viewerId && c.is_anonymous && c.post_specific_anon_id)
            ?.post_specific_anon_id ?? null
        : null;
      const now = new Date().toISOString();

      const optimistic: CommentVM = {
        id,
        post_id: postId,
        user_id: viewerId,
        content: content.trim(),
        parent_comment_id: parentId && !parentId.startsWith("temp-") ? parentId : null,
        is_anonymous: isAnonymous,
        is_deleted: false,
        created_at: now,
        updated_at: now,
        post_specific_anon_id: knownAnonId,
        user: queryClient.getQueryData<Profile | null>(["current-user-profile", viewerId]) ?? undefined,
        score: 0,
        user_vote: null,
        _pending: true,
      };

      // Filter by id first: a retry of the same submission reuses its id.
      queryClient.setQueryData<CommentVM[]>(listKey, (old) => [
        ...(old ?? []).filter((c) => c.id !== id),
        optimistic,
      ]);
    },
    onError: (error: unknown, variables: CreateCommentInput) => {
      removeComment(variables.id);
      logger.error("Error posting comment", error as Error);
      const message =
        error instanceof Error
          ? error.message
          : "Failed to post comment. Please try again.";

      let errorMessage = message;
      if (message.includes("rate limit")) {
        errorMessage = "You're posting too fast. Please wait a moment.";
      } else if (message.includes("network") || message.includes("timeout")) {
        errorMessage = "Network error. Please check your connection.";
      }

      Alert.alert("Error", errorMessage);
    },
    onSuccess: async (newComment: CommentNode) => {
      if (!viewerId || !postId) return;

      const profile = await getViewerProfile();
      if (profile?.university_id) {
        logActivity("comment_created", profile.university_id, viewerId);
      }

      // Swap the optimistic entry for the server row (which carries the
      // server-assigned post_specific_anon_id). No refetch needed.
      const confirmed: CommentVM = {
        ...newComment,
        user: profile,
        score: 0,
        user_vote: null,
        _pending: false,
      };
      queryClient.setQueryData<CommentVM[]>(listKey, (old) => {
        const list = old ?? [];
        return list.some((c) => c.id === confirmed.id)
          ? list.map((c) => (c.id === confirmed.id ? confirmed : c))
          : [...list, confirmed];
      });

      queryClient.invalidateQueries({ queryKey: ["post", postId] });
      if (communityId !== undefined) {
        queryClient.invalidateQueries({
          predicate: feedKeys.belongsToCommunity(communityId),
          refetchType: "none",
        });
      } else {
        queryClient.invalidateQueries({
          queryKey: ["posts", "feed"],
          refetchType: "none",
        });
      }
      // Refetch immediately if Profile's "user-posts" query is mounted (default
      // 'active' behavior) — Profile's tab screen never unmounts once visited,
      // so 'none' here used to leave this permanently stale for the rest of the
      // session once Profile had already been opened once (Phase 7.2).
      queryClient.invalidateQueries({
        queryKey: ["user-posts", viewerId],
      });
    },
  });
}

