import { useMutation, UseMutationResult, useQueryClient } from "@tanstack/react-query";
import { supabase } from "../lib/supabase";
import { logger } from "../utils/logger";
import { logActivity } from "../utils/activityLogger";
import { Alert } from "react-native";
import { feedKeys } from "../features/communities/data/queryKeys";
import {
  buildPostAuthorContext,
  resolvePostAuthorDisplay,
} from "../utils/entityDisplay";
import {
  normalizePostBody,
  normalizePostTitle,
} from "../utils/postValidation";

type CreatePostVariables = {
  imagePath: string | undefined;
  imagePaths?: string[];
  imageAspectRatio?: number | null;
  postContent: string;
  postTitle: string;
  postLocation: string;
  postIsAnonymous: boolean;
  postCategory: "lost" | "found";
  pollOptions?: string[];
  /** Resolved at submit time so community posts never miss their target feed. */
  communityId?: string | null;
  /**
   * Idempotency key for this submission (Phase 2). Generated by the caller
   * (create-post.tsx) and held stable across retries of the same content —
   * see the comment on `lastAttemptRef` there for why the id can't be
   * generated here, inside the mutation.
   */
  id: string;
};

type CreatePostOptions = {
  isLostFound: boolean;
  repostId?: string | string[];
  currentUserId: string | null | undefined;
  universityId?: string | null;
  universityDomain?: string | null;
  communityName?: string | null;
  communityAvatarUrl?: string | null;
  /** Fallback when communityId is not passed in mutate() variables. */
  communityId?: string | null;
  /** Current user's real profile, used for the optimistic post's author display. */
  username?: string | null;
  avatarUrl?: string | null;
};

export function useCreatePostMutation(options: CreatePostOptions): UseMutationResult<any, unknown, CreatePostVariables> {
  const {
    isLostFound,
    repostId,
    currentUserId,
    universityId,
    universityDomain,
    communityName,
    communityAvatarUrl,
    communityId: defaultCommunityId,
    username,
    avatarUrl,
  } = options;
  const queryClient = useQueryClient();

  const resolvedRepostId =
    typeof repostId === "string" ? repostId : Array.isArray(repostId) ? repostId[0] : undefined;

  return useMutation({
    mutationKey: ["create-post"],
    mutationFn: async (variables: CreatePostVariables) => {
      if (!currentUserId) {
        throw new Error("You must be logged in to create a post.");
      }

      const {
        postContent,
        postTitle,
        postLocation,
        postIsAnonymous,
        postCategory,
        pollOptions,
        imagePath,
        imagePaths,
        imageAspectRatio,
        communityId: submitCommunityId,
        id: idempotencyId,
      } =
        variables;

      const effectiveCommunityId = submitCommunityId ?? defaultCommunityId ?? null;

      const normalizedImagePaths = (imagePaths ?? []).filter(
        (path): path is string => Boolean(path?.trim()),
      );
      const primaryImagePath = normalizedImagePaths[0] ?? imagePath;
      const normalizedTitle = normalizePostTitle(postTitle);
      const normalizedContent = normalizePostBody(postContent);

      if (!resolvedRepostId && !normalizedContent && !primaryImagePath) {
        throw new Error("Content is required");
      }

      if (isLostFound && !postLocation.trim()) {
        throw new Error("Location is required for lost & found posts");
      }

      const postPayload = {
        id: idempotencyId,
        content: normalizedContent,
        post_type: isLostFound ? "lost_found" : "feed",
        image_url: primaryImagePath || null,
        image_urls: normalizedImagePaths.length > 0 ? normalizedImagePaths : null,
        image_aspect_ratio: imageAspectRatio ?? null,
        is_anonymous: isLostFound ? false : postIsAnonymous,
        ...(normalizedTitle && { title: normalizedTitle }),
        ...(isLostFound && {
          category: postCategory,
          location: postLocation.trim(),
        }),
        ...(effectiveCommunityId && { community_id: effectiveCommunityId }),
        ...(resolvedRepostId && {
          reposted_from_post_id: resolvedRepostId,
        }),
        ...(!isLostFound &&
          pollOptions &&
          pollOptions.length >= 2 && {
            poll_options: pollOptions,
          }),
      };

      const supabaseUrl = process.env.EXPO_PUBLIC_SUPABASE_URL!;
      const functionUrl = `${supabaseUrl}/functions/v1/create-post`;

      const {
        data: { session },
      } = await supabase.auth.getSession();

      if (!session?.access_token) {
        throw new Error("You must be logged in to create a post.");
      }

      const response = await fetch(functionUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${session.access_token}`,
          apikey: process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY!,
        },
        body: JSON.stringify(postPayload),
      });

      const responseData = await response.json();

      if (!response.ok) {
        const errorMessage =
          responseData?.error || responseData?.message || "Failed to create post";
        throw new Error(errorMessage);
      }

      if (responseData?.error) {
        throw new Error(responseData.error);
      }

      if (!responseData || !responseData.id) {
        throw new Error("Invalid response from server");
      }

      return responseData;
    },
    // No onMutate / optimistic insert (Phase 7.6 — product decision: the
    // user stays on the create-post screen, seeing only the honest
    // submission-progress states from create-post.tsx, until the post is
    // genuinely confirmed AND reflected in the feed — never a temp
    // placeholder that then gets swapped for the real row once they've
    // already navigated away). Everything below runs only after the server
    // has actually created the post.
    onError: (error) => {
      logger.error("Error creating post", error as Error);
      const message =
        error instanceof Error
          ? error.message
          : "Failed to create post. Please try again.";
      Alert.alert("Error", message);
    },
    onSuccess: async (data, variables) => {
      if (isLostFound) {
        // Awaited — onSuccess's returned promise is awaited internally by
        // TanStack Query before mutateAsync() resolves, so create-post.tsx
        // does not navigate away until the Lost & Found list has actually
        // refetched and contains the new post (not merely until the
        // refetch was *requested*).
        await queryClient.invalidateQueries({
          queryKey: ["posts", "lost_found"],
        });
      } else {
        const effectiveCommunityId =
          variables.communityId ?? defaultCommunityId ?? null;
        const feedCacheKey = feedKeys.list(
          "new",
          "",
          universityId ?? undefined,
          effectiveCommunityId,
        );

        const authorDisplay = resolvePostAuthorDisplay(
          buildPostAuthorContext({
            isAnonymous: variables.postIsAnonymous,
            username,
            avatarUrl,
            universityDomain,
            communityId: effectiveCommunityId,
            communityName,
            communityAvatarUrl,
            userId: currentUserId,
            currentUserId,
          }),
        );

        // Built from the server-confirmed response (`data`) only — never
        // written to the cache before this point — so Campus/community
        // feeds never show a placeholder version of the post. Display-only
        // fields the server response doesn't carry (username, avatar,
        // community name, vote/comment counts) are filled in client-side,
        // same as the old optimistic-post reconciliation did; every
        // server-authoritative field in `data` wins via the spread below.
        const confirmedPost = {
          user_id: currentUserId || "",
          content: variables.postContent.trim(),
          image_url: variables.imagePath || null,
          image_urls:
            variables.imagePaths && variables.imagePaths.length > 0
              ? variables.imagePaths
              : variables.imagePath
                ? [variables.imagePath]
                : null,
          image_aspect_ratio: variables.imageAspectRatio ?? null,
          title: variables.postTitle.trim() || null,
          category: null,
          location: null,
          post_type: "feed",
          community_id: effectiveCommunityId,
          community_name: communityName ?? null,
          community_avatar_url: communityAvatarUrl ?? null,
          university_id: universityId ?? "",
          university_domain: universityDomain ?? "",
          is_anonymous: variables.postIsAnonymous,
          is_deleted: false,
          is_edited: false,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
          edited_at: null,
          view_count: 0,
          username: authorDisplay.displayName,
          avatar_url: avatarUrl ?? null,
          is_verified: false,
          is_banned: false,
          comment_count: 0,
          vote_score: 0,
          user_vote: null,
          reposted_from_post_id: resolvedRepostId || null,
          repost_comment: resolvedRepostId ? variables.postContent.trim() : null,
          repost_count: 0,
          original_post_id: null,
          original_title: null,
          original_content: null,
          original_user_id: null,
          original_author_username: null,
          original_author_avatar: null,
          original_is_anonymous: null,
          original_created_at: null,
          ...data,
          post_id: data.id,
        };

        queryClient.setQueryData(feedCacheKey, (oldData: any) => {
          if (!oldData) {
            return {
              pages: [[confirmedPost]],
              pageParams: [0],
            };
          }

          const pages = Array.isArray(oldData.pages) ? oldData.pages : [];
          const newPages = pages.length
            ? [[confirmedPost, ...pages[0]], ...pages.slice(1)]
            : [[confirmedPost]];

          return {
            ...oldData,
            pages: newPages,
          };
        });
      }
      if (universityId && currentUserId) {
        logActivity("post_created", universityId, currentUserId);
      }
    },
    onSettled: (_data, _error, variables) => {
      if (!isLostFound) {
        const communityId = variables?.communityId ?? defaultCommunityId ?? null;
        queryClient.invalidateQueries({
          predicate: feedKeys.belongsToCommunity(communityId),
          refetchType: "none",
        });
      }
    },
  });
}

